# Generated by Django on 2025-01-XX XX:XX

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import customregistration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(help_text='Primer apellido del usuario', max_length=100, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, help_text='Segundo apellido del usuario (opcional)', max_length=100, verbose_name='Segundo Apellido')),
                ('numero_telefono', models.CharField(help_text='Número de teléfono a 10 dígitos', max_length=10, validators=[customregistration.models.validate_phone], verbose_name='Número de Teléfono')),
                ('estado', models.CharField(help_text='Estado de residencia', max_length=100, verbose_name='Estado')),
                ('municipio', models.CharField(help_text='Municipio de residencia', max_length=100, verbose_name='Municipio')),
                ('nombre_escuela', models.CharField(help_text='Nombre completo de la institución educativa', max_length=200, verbose_name='Nombre de la Escuela')),
                ('cct', models.CharField(help_text='Clave de Centro de Trabajo (10 caracteres)', max_length=10, validators=[customregistration.models.validate_cct], verbose_name='CCT')),
                ('grado', models.CharField(help_text='Grado escolar actual', max_length=50, verbose_name='Grado')),
                ('curp', models.CharField(help_text='Clave Única de Registro de Población (18 caracteres)', max_length=18, unique=True, validators=[customregistration.models.validate_curp], verbose_name='CURP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Personalizado de Usuario',
                'verbose_name_plural': 'Perfiles Personalizados de Usuarios',
                'db_table': 'customregistration_usercustomprofile',
            },
        ),
    ]
